# Generated by Django 4.0.3 on 2022-05-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp4app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdata',
            old_name='orphanageaddress',
            new_name='orphanaddress',
        ),
    ]
